name: Build Project

on:
  push:
    branches:
    - develop
    - master
    paths:
    - 'Tools/UnityLicense.ulf'
    - 'UnityProject/**'
    - '.github/workflows/main.yml'
    - 'Docker/**'
  pull_request:
    branches:
    - develop
    - master
    paths:
    - 'Tools/UnityLicense.ulf'
    - 'UnityProject/**'
    - '.github/workflows/main.yml'

jobs:

  ########## HOW TO UPDATE UNITY_LICENSE ##########
  # The job below is only used to request a new activation file
  #
  # !!! WARNING: Use a throw away Unity account for this since anyone will have access to the license file !!!
  #
  # If you need a new one follow these steps:
  #   - Uncomment the job below and run it
  #   - Download the manual activation file that appears as an artifact in a zip (Unity_v20XX.x.alf).
  #   - Visit license.unity3d.com, sign in and upload it.
  #   - You should now receive your license file (Unity_v20XX.x.ulf) as a download.
  #   - Replace UnityLicense.ulf in the Tools directory with it.
  #   - Make sure LICENSE_FILE_PATH in the 'Setup license' step still points to it.

   # Request license file job
   requestManualActivationFile:
     name: Request manual activation file
     runs-on: ubuntu-latest
     steps:
       # Request manual activation file
       - name: Request manual activation file
         uses: webbertakken/unity-request-manual-activation-file@v1.1
         id: getManualLicenseFile
         with:
           unityVersion: 2019.4.7f1
       # Upload artifact (Unity_v20XX.X.XXXX.alf)
       - name: Expose as artifact
         uses: actions/upload-artifact@v1
         with:
           name: ${{ steps.getManualLicenseFile.outputs.filePath }}
           path: ${{ steps.getManualLicenseFile.outputs.filePath }}
